import 'package:flutter/material.dart';
import 'package:k16_booking/main.dart';

void main() {
  runApp(const MyApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          CustSettingAccount(),
        ]),
      ),
    );
  }
}

class CustSettingAccount extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 932,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.black,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(40),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 145,
                top: 62,
                child: Container(
                  width: 129,
                  height: 129,
                  decoration: ShapeDecoration(
                    color: const Color(0x66F2C94C),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 150,
                top: 67,
                child: Container(
                  width: 119,
                  height: 119,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 4,
                        color: const Color(0xFFF2C94C),
                      ),
                      borderRadius: BorderRadius.circular(100),
                    ),
                  ),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 111,
                top: 202,
                child: SizedBox(
                  width: 195,
                  height: 19,
                  child: Text(
                    'Customer name',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w800,
                      height: 1.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -4,
                top: 951,
                child: Container(
                  width: 436,
                  height: 87,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/436x87"),
                      fit: BoxFit.cover,
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 436,
                          height: 87,
                          decoration: ShapeDecoration(
                            color: Colors.black,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(10),
                                topRight: Radius.circular(10),
                              ),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x0C54575C),
                                blurRadius: 3,
                                offset: Offset(2, -2),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 348.80,
                        top: 26.10,
                        child: Container(
                          width: 34.88,
                          height: 34.80,
                          child: Stack(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 42,
                top: 284,
                child: Container(
                  width: 45,
                  height: 45,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(border: Border.all(width: 1)),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 94,
                top: 295,
                child: Text(
                  'Edit profil',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w700,
                    height: 1.10,
                  ),
                ),
              ),
              Positioned(
                left: 54.66,
                top: 346,
                child: SizedBox(
                  width: 137.78,
                  height: 23,
                  child: Text(
                    'Nama\n',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 55.65,
                top: 452,
                child: SizedBox(
                  width: 137.78,
                  height: 23,
                  child: Text(
                    'Username',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 54,
                top: 563,
                child: SizedBox(
                  width: 216,
                  height: 23,
                  child: Text(
                    'Konfirmasi Password',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 53.68,
                top: 674,
                child: SizedBox(
                  width: 137.78,
                  height: 23,
                  child: Text(
                    'Password',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 122,
                top: 389,
                child: SizedBox(
                  width: 186,
                  height: 23,
                  child: Opacity(
                    opacity: 0.60,
                    child: Text(
                      'Masukkan nama anda',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 16,
                        fontFamily: 'Poppins',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 76,
                top: 499,
                child: SizedBox(
                  width: 219,
                  height: 23,
                  child: Opacity(
                    opacity: 0.60,
                    child: Text(
                      'Masukkan username anda',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 16,
                        fontFamily: 'Poppins',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 92.21,
                top: 609,
                child: SizedBox(
                  width: 296.01,
                  height: 23,
                  child: Opacity(
                    opacity: 0.60,
                    child: Text(
                      'Masukkan password anda',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 16,
                        fontFamily: 'Poppins',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 76,
                top: 721,
                child: SizedBox(
                  width: 296.01,
                  height: 23,
                  child: Opacity(
                    opacity: 0.60,
                    child: Text(
                      'Masukkan ulang password anda',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 16,
                        fontFamily: 'Poppins',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 252,
                top: 794.61,
                child: SizedBox(
                  width: 128.33,
                  height: 14.64,
                  child: Text(
                    'Simpan',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 195,
                top: 975,
                child: Container(
                  width: 38,
                  height: 38,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/38x38"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -4,
                top: 0,
                child: Container(
                  width: 428,
                  padding: const EdgeInsets.only(
                    top: 21,
                    left: 24,
                    right: 24,
                    bottom: 19,
                  ),
                  decoration: BoxDecoration(color: Colors.black),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 154,
                    children: [
                      Expanded(
                        child: Container(
                          height: 22,
                          padding: const EdgeInsets.only(top: 1.50),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 10,
                            children: [
                              Text(
                                '9:41',
                                textAlign: TextAlign.center,
                                style: TextStyle(
                                  color: Colors.white /* Miscellaneous-Segmented-Control---Selected-Fill */,
                                  fontSize: 17,
                                  fontFamily: 'SF Pro',
                                  fontWeight: FontWeight.w600,
                                  height: 1.29,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Expanded(
                        child: Container(
                          height: 22,
                          padding: const EdgeInsets.only(top: 1, right: 1),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 7,
                            children: [
                              Container(
                                width: 27.33,
                                height: 13,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Opacity(
                                        opacity: 0.35,
                                        child: Container(
                                          width: 25,
                                          height: 13,
                                          decoration: ShapeDecoration(
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(
                                                width: 1,
                                                color: Colors.white /* Miscellaneous-Sidebar-Fill---Selected */,
                                              ),
                                              borderRadius: BorderRadius.circular(4.30),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 2,
                                      top: 2,
                                      child: Container(
                                        width: 21,
                                        height: 9,
                                        decoration: ShapeDecoration(
                                          color: Colors.white /* Miscellaneous-Sidebar-Fill---Selected */,
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(2.50),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: -4,
                top: 847,
                child: Container(
                  width: 436,
                  height: 87,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/436x87"),
                      fit: BoxFit.cover,
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 436,
                          height: 87,
                          decoration: ShapeDecoration(
                            color: Colors.black,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(10),
                                topRight: Radius.circular(10),
                              ),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x0C54575C),
                                blurRadius: 3,
                                offset: Offset(2, -2),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 348.80,
                        top: 26.10,
                        child: Container(
                          width: 34.88,
                          height: 34.80,
                          child: Stack(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 191,
                top: 871,
                child: Container(
                  width: 38,
                  height: 38,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/38x38"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 61,
                top: 235,
                child: SizedBox(
                  width: 278,
                  height: 31,
                  child: Text(
                    'Kembali ke Halaman Profil',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                      height: 1.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 24,
                top: 234,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                  height: 33,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}