import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          CustProfilAccount(),
        ]),
      ),
    );
  }
}

class CustProfilAccount extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 926,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.black,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(40),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: -8,
                top: 839,
                child: Container(
                  width: 436,
                  height: 87,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/436x87"),
                      fit: BoxFit.cover,
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 436,
                          height: 87,
                          decoration: ShapeDecoration(
                            color: Colors.black,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(10),
                                topRight: Radius.circular(10),
                              ),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x0C54575C),
                                blurRadius: 3,
                                offset: Offset(2, -2),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 348.80,
                        top: 26.10,
                        child: Container(
                          width: 34.88,
                          height: 34.80,
                          child: Stack(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 148.02,
                top: 64,
                child: Container(
                  width: 129,
                  height: 128.68,
                  decoration: ShapeDecoration(
                    color: const Color(0x66F2C94C),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 153.09,
                top: 68.92,
                child: Container(
                  width: 118.85,
                  height: 118.85,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 4,
                        color: const Color(0xFFF2C94C),
                      ),
                      borderRadius: BorderRadius.circular(100),
                    ),
                  ),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 116.02,
                top: 204.66,
                child: SizedBox(
                  width: 195,
                  height: 18.95,
                  child: Text(
                    'Customer name',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w800,
                      height: 1.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 50.20,
                top: 235.58,
                child: Container(
                  width: 45,
                  height: 44.89,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(border: Border.all(width: 1)),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 61.20,
                top: 292.44,
                child: SizedBox(
                  width: 195,
                  height: 18.95,
                  child: Text(
                    'Nama Lengkap',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w800,
                      height: 1.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 104.20,
                top: 239.57,
                child: SizedBox(
                  width: 137,
                  height: 29.93,
                  child: Text(
                    'Profil',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 64.20,
                top: 329.35,
                child: SizedBox(
                  width: 199,
                  height: 22.94,
                  child: Opacity(
                    opacity: 0.60,
                    child: Text(
                      'Nama admin Ex. Budi',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 16,
                        fontFamily: 'Poppins',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 55.81,
                top: 389.20,
                child: SizedBox(
                  width: 137.01,
                  height: 22.94,
                  child: Text(
                    'Username',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 64.02,
                top: 437.09,
                child: SizedBox(
                  width: 244,
                  height: 22.94,
                  child: Opacity(
                    opacity: 0.60,
                    child: Text(
                      'Username Ex. Admin1',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 16,
                        fontFamily: 'Poppins',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 146,
                top: 723,
                child: SizedBox(
                  width: 141,
                  height: 29,
                  child: Text(
                    'Logout',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 26,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                      height: 0.85,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 100.01,
                top: 709.37,
                child: Container(
                  width: 48.25,
                  height: 48.25,
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 191,
                top: 863,
                child: Container(
                  width: 38,
                  height: 38,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/38x38"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 112,
                top: 632,
                child: Container(
                  width: 203,
                  height: 47,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFFEDA0C),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(13),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 116,
                top: 637,
                child: Container(
                  width: 55,
                  height: 34,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/55x34"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 181,
                top: 643,
                child: SizedBox(
                  width: 87,
                  height: 23,
                  child: Opacity(
                    opacity: 0.60,
                    child: Text(
                      'Edit Profile',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 16,
                        fontFamily: 'Poppins',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -4,
                top: 2,
                child: Container(
                  width: 428,
                  padding: const EdgeInsets.only(
                    top: 21,
                    left: 24,
                    right: 24,
                    bottom: 19,
                  ),
                  decoration: BoxDecoration(color: Colors.black),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 154,
                    children: [
                      Expanded(
                        child: Container(
                          height: 22,
                          padding: const EdgeInsets.only(top: 1.50),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 10,
                            children: [
                              Text(
                                '9:41',
                                textAlign: TextAlign.center,
                                style: TextStyle(
                                  color: Colors.white /* Miscellaneous-Segmented-Control---Selected-Fill */,
                                  fontSize: 17,
                                  fontFamily: 'SF Pro',
                                  fontWeight: FontWeight.w600,
                                  height: 1.29,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Expanded(
                        child: Container(
                          height: 22,
                          padding: const EdgeInsets.only(top: 1, right: 1),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 7,
                            children: [
                              Container(
                                width: 27.33,
                                height: 13,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Opacity(
                                        opacity: 0.35,
                                        child: Container(
                                          width: 25,
                                          height: 13,
                                          decoration: ShapeDecoration(
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(
                                                width: 1,
                                                color: Colors.white /* Miscellaneous-Sidebar-Fill---Selected */,
                                              ),
                                              borderRadius: BorderRadius.circular(4.30),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 2,
                                      top: 2,
                                      child: Container(
                                        width: 21,
                                        height: 9,
                                        decoration: ShapeDecoration(
                                          color: Colors.white /* Miscellaneous-Sidebar-Fill---Selected */,
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(2.50),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}